version: 2
jobs:
  accept_library_licenses: # testing license
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - run: cp -r licenses/. $ANDROID_HOME/licenses
  build:  # build creation and dependencies testing
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  build_release:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run: make build
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #- run:
          #name: Initial build
          #command: ./gradlew clean assembleRelease --no-daemon --stacktrace
      - store_artifacts:
            path: /bin/final_build
      #- store_artifacts:
          #path: app/build/outputs/apk/
          #destination: apks/

workflows:
  version: 2
  build_and_test:
    jobs:
      # accept_library_licenses
      # build
      - build_release
